### ISSUE TITLE
bugs when compiling lammps-17Nov16

### ISSUE THREAD

**Issue by pincher-chen** [Atomistica/atomistica#11]
mpicxx  -g -O3 -openmp -DLAMMPS_MEMALIGN=64 -no-offload -xHost -fno-alias -ansi-alias -restrict -override-limits  -DLAMMPS_GZIP -DLAMMPS_JPEG -DLMP_MPIIO  -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1 -I/usr/local/mpi3-dynamic/include -DFFT_MKL -DFFT_SINGLE -I/HOME/intel/composer_xe_2013_sp1.2.144/mkl/include/fftw -I/HOME/nscc_ts_1/tars/lammps-17Nov16/lib/atomistica/src/support -I/HOME/nscc_ts_1/tars/lammps-17Nov16/lib/atomistica/build_lammps    -c ../pair_atomistica.cpp
../pair_atomistica.cpp(392): error: class "LAMMPS_NS::NeighList" has no member "ghost"
    if (!list->ghost) {
               ^

compilation aborted for ../pair_atomistica.cpp (code 2)
make[1]: *** [pair_atomistica.o] Error 2
make[1]: Leaving directory `/HOME/nscc_ts_1/tars/lammps-17Nov16/src/Obj_intel_cpu_atomistica'
make: *** [intel_cpu_atomistica] Error 2

**Comment by pastewka** [comment]
Please change "ghost" to "ghostflag". This was changed in more recent LAMMPS versions.

Lars


________________________________
Von: Pin Chen <notifications@github.com>
Gesendet: 12.06.2017 3:58 vorm.
An: Atomistica/atomistica
Cc: Subscribed
Betreff: [Atomistica/atomistica] bugs when compiling lammps-17Nov16 (#11)
