### ISSUE TITLE
Error while compiling lammps : undefined reference to `potential_classes'

### ISSUE THREAD

**Issue by mohitmrsharma** [Atomistica/atomistica#23]
While compiling LAMMPS with atomistica, the process stops at the following error 
Kindly point me in the right direction 
I am using LAMMPS 16 Mar 18 version 
pair_atomistica.o:pair_atomistica.cpp:(.rdata$.refptr.potential_classes[.refptr.potential_classes]+0x0): undefined reference to `potential_classes'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:88: ../lmp_serial] Error 1
make[1]: Leaving directory '/cygdrive/c/lammpsatom/src/Obj_serial'
make: *** [Makefile:172: serial] Error 2

**Comment by pastewka** [comment]
You forgot to link with the Atomistica library. There needs to be a „-latomistica“ in your link line, as described in step 4 here:

https://github.com/Atomistica/atomistica/blob/master/README.LAMMPS.md
