### ISSUE TITLE
Standalone: SlidingP + global langevin1D lead to non-rigidity of top-rigid atoms

### ISSUE THREAD

**Issue by threich** [Atomistica/atomistica#25]
When using the standalone code with

`  Langevin1D {
...
  };
`
and
`  SlidingP {
...
 };`

the rigid atoms of the upper slab are not rigid (in the attached example the upper H atoms start to move very slowly in the y-direction).  I suspect that the Langevin random force is added after applying the slidingP constraint. Due to the high mass of these atoms the movement can easily be overlooked.

The problem can be circumvented by using 
`  LocalLangevin1D {
...
  };
` 
and setting the dissipation and temperature of the rigid atoms to 0. 

[atoms.zip](https://github.com/Atomistica/atomistica/files/3793116/atoms.zip)

**Comment by tkuwa** [comment]
I fixed the code. Langevin1D should work correctly with SlidingP.
